### PR TITLE
Prisma2: Use `reduceAreas` for area labels again

### PR DESCRIPTION
**Pull request by janpio**
We didn't use `reduceAreas` for Prisma2 yet, but it makes sense to do so.

(Also add `area/spec-meta`)

### CODE REVIEW

**Comment by janpio** [comment]
Interesting output from dry-run:

```
prisma/specs
This is an autogenerated report for your project.
(dry run: "true")

New Labels: (1)
- area/spec-meta

Updated Labels: (12)
- area/photonjs
- area/lift
- area/schema
- area/cli
- area/introspection
- area/sdk
- area/studio
- area/query-engine
- area/migration-engine
- area/spec-infra
- area/process
- area/connector

Removed Labels: (0)
No removed labels.

```

image

I am not sure why something has to be updated there tbh :/

**Comment by janpio** [comment]
HOLD, please don't merge. I want to investigate the label updates - could be #34 again

**Comment by janpio** [comment]
(Actually, no way to find out but by merging, so... Leeeeeroy!)

**Comment by divyenduz** [comment]
I think it detects changes because `color` key is missing in `reduceAreas` output. 

`https://github.com/prisma/prisma-label-sync/pull/60/files#diff-cdf4e269e803f720664aa837a25a2994R28`

**Comment by janpio** [comment]
Shouldn't `reduceAreas` put that in there again so `label-sync` does get the color and understand what it should do?

**Comment by janpio** [comment]
Haha, the yellow is slightly different - that is why it recognized a change :p

**Pull request merged**
